# This file was generated by the {rix} R package v0.17.4 on 2026-02-19
# with following call:
# >rix::rix(date = "2026-01-05",
#  > r_pkgs = c(r_pkgs,
#  > bioc_pkgs),
#  > system_pkgs = system_pkgs,
#  > project_path = ".",
#  > overwrite = TRUE,
#  > shell_hook = shell_hook,
#  > r_ver = "4.5.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-01-05.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      air
      arrow
      aws_s3
      cli
      crew
      DBI
      dbplyr
      DESeq2
      devtools
      dplyr
      DT
      duckdb
      edgeR
      GenomicDataCommons
      gert
      ggplot2
      gh
      glue
      knitr
      limma
      logger
      mirai
      nanonext
      nanoparquet
      pkgdown
      plotly
      rmarkdown
      spelling
      stringr
      styler
      SummarizedExperiment
      survival
      tarchetypes
      targets
      TCGAbiolinks
      testthat
      tibble
      tidyverse
      usethis;
  };
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      bc
      btop
      cacert
      clang
      curl
      curlMinimal
      direnv
      duckdb
      gcc
      gettext
      gh
      git
      glibcLocales
      glpk
      gnupg
      htop
      jq
      less
      libgcc
      libiconv
      libxml2
      locale
      nano
      nix
      openssl
      pandoc
      R
      toybox
      tree
      unzip
      zlib
      which;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs system_packages ];
    shellHook = ''
    export R_MAKEVARS_USER=/dev/null
printf 'CoMMpass environment ready.
'
  '';
  }; 
in
  {
    inherit pkgs shell;
  }
