# This file was generated by the {rix} R package v0.18.1 on 2026-03-15
# with following call:
# >rix::rix(date = date,
#  > r_pkgs = c(r_pkgs,
#  > bioc_pkgs),
#  > system_pkgs = system_pkgs,
#  > project_path = ".",
#  > overwrite = TRUE,
#  > shell_hook = shell_hook,
#  > r_ver = "4.5.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-02-02.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      air
      AnnotationDbi
      apeglm
      arrow
      aws_s3
      cli
      crew
      DBI
      dbplyr
      DESeq2
      devtools
      dplyr
      DT
      duckdb
      edgeR
      fgsea
      GenomicDataCommons
      gert
      ggplot2
      gh
      glue
      here
      htmltools
      jsonlite
      knitr
      limma
      logger
      mirai
      nanonext
      nanoparquet
      org_Hs_eg_db
      pkgdown
      plotly
      plumber
      quarto
      rmarkdown
      S4Vectors
      scales
      spelling
      stringr
      styler
      SummarizedExperiment
      survival
      tarchetypes
      targets
      TCGAbiolinks
      testthat
      tibble
      tidyverse
      usethis
      visNetwork;
  };
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      bc
      btop
      cacert
      clang
      curl
      curlMinimal
      direnv
      duckdb
      gcc
      gettext
      gh
      git
      glibcLocales
      glpk
      gnupg
      htop
      jq
      less
      libgcc
      libiconv
      libxml2
      locale
      nano
      nix
      openssl
      pandoc
      qpdf
      quarto
      R
      toybox
      tree
      unzip
      zlib
      which;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs system_packages ];
    shellHook = ''
    _R_HASH=$(basename $(dirname $(dirname $(which R))))
_FILTERED_LIBS=$(echo "$R_LIBS_SITE" | tr ":" "\n" | while read _L; do
  if [ -d "$_L" ]; then
    _SO=$(find "$_L" -name "*.so" -maxdepth 4 2>/dev/null | head -1)
    if [ -n "$_SO" ]; then
      if otool -L "$_SO" 2>/dev/null | grep -q "$_R_HASH"; then
        echo "$_L"
      fi
    else
      echo "$_L"
    fi
  fi
done | tr "\n" ":" | sed 's/:$//')
export R_LIBS_SITE="$_FILTERED_LIBS"
unset R_LIBS
export R_MAKEVARS_USER=/dev/null
printf 'CoMMpass environment ready.\n'
  '';
  }; 
in
  {
    inherit pkgs shell;
  }
