# This file was generated by the {rix} R package v0.17.2 on 2026-01-13
# with following call:
# >rix::rix(date = latest,
#  > r_pkgs = c(r_pkgs,
#  > bioc_pkgs),
#  > system_pkgs = system_pkgs,
#  > git_pkgs = gh_pkgs,
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > shell_hook = shell_hook,
#  > r_ver = "4.4.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2024-12-14.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      air
      aws_s3
      aws_signature
      dbplyr
      devtools
      dplyr
      duckdb
      forcats
      fs
      GenomicDataCommons
      gert
      ggplot2
      gh
      glue
      here
      logger
      mirai
      nanonext
      pkgdown
      purrr
      readr
      rix
      spelling
      stringr
      styler
      SummarizedExperiment
      tarchetypes
      targets
      TCGAbiolinks
      testthat
      tibble
      tictoc
      tidyr
      usethis;
  };
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      awscli2
      bc
      btop
      cacert
      clang
      curl
      curlMinimal
      direnv
      duckdb
      gcc
      gettext
      gh
      git
      glibcLocales
      glpk
      gnupg
      htop
      jq
      less
      libgcc
      libiconv
      libxml2
      locale
      nano
      nix
      openssl
      pandoc
      quarto
      R
      texliveBasic
      toybox
      tree
      unzip
      zlib;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs system_packages ];
    shellHook = "
# =============================================================================
# CoMMpass Analysis Environment - Shell Hook
# =============================================================================

valid_home=1
case $HOME in
  ''|*'$'*) valid_home=0 ;;
  /*) ;;
  *) valid_home=0 ;;
esac

user_ok=0
case $USER in
  ''|*'$'*) user_ok=0 ;;
  *) if [ -d /Users/$USER ]; then user_ok=1; fi ;;
esac

if [ $valid_home -ne 1 ] && [ $user_ok -eq 1 ]; then
  HOME=/Users/$USER
  export HOME
  valid_home=1
fi

if [ $valid_home -ne 1 ]; then
  printf '%s\n' 'Skipping environment setup due to invalid HOME.'
else
  # Disable user Makevars to prevent Homebrew path conflicts
  export R_MAKEVARS_USER=/dev/null

  # Set up AWS credentials location (if using AWS for CoMMpass data)
  export AWS_SHARED_CREDENTIALS_FILE=$HOME/.aws/credentials
  export AWS_CONFIG_FILE=$HOME/.aws/config

  printf '%s\n' '=== CoMMpass Analysis Environment ==='
  printf '%s\n' 'Data access options:'
  printf '%s\n' ' 1. AWS S3: aws s3 ls --no-sign-request s3://gdc-mmrf-commpass-phs000748-2-open/'
  printf '%s\n' ' 2. GDC API: TCGAbiolinks::GDCquery(project=MMRF-COMMPASS)'
  printf '%s\n' ' 3. MMRF-RG: Register at research.themmrf.org'
  printf '%s\n' ''
fi

unset CI
printf '%s\n' 'CoMMpass environment ready.'
";
  }; 
in
  {
    inherit pkgs shell;
  }
