# This file was generated by the {rix} R package v0.17.2 on 2026-01-24
# with following call:
# >rix::rix(r_ver = "4.5.2",
#  > r_pkgs = c(r_pkgs,
#  > bioc_pkgs),
#  > system_pkgs = system_pkgs,
#  > git_pkgs = gh_pkgs,
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > shell_hook = shell_hook)
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-01-19.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      AnnotationDbi
      arrow
      aws_s3
      aws_signature
      batchelor
      BiocManager
      Biostrings
      celldex
      circlize
      clusterProfiler
      clustree
      ComplexHeatmap
      cowplot
      crew
      data_table
      dbplyr
      DESeq2
      devtools
      DOSE
      DropletUtils
      DT
      dtplyr
      duckdb
      edgeR
      enrichplot
      fgsea
      flextable
      fs
      furrr
      future
      GenomicDataCommons
      GenomicRanges
      gert
      ggpubr
      ggrepel
      gh
      glue
      gt
      harmony
      here
      httr2
      infercnv
      janitor
      knitr
      limma
      logger
      mirai
      msigdbr
      nanonext
      org_Hs_eg_db
      patchwork
      pec
      pheatmap
      pkgdown
      progressr
      RColorBrewer
      ReactomePA
      remotes
      riskRegression
      rmarkdown
      rtracklayer
      scater
      scran
      sctransform
      Seurat
      SeuratObject
      SingleCellExperiment
      SingleR
      skimr
      spelling
      styler
      SummarizedExperiment
      survival
      survivalAnalysis
      survminer
      tarchetypes
      targets
      TCGAbiolinks
      testthat
      tictoc
      tidyverse
      timeROC
      TxDb_Hsapiens_UCSC_hg38_knownGene
      usethis
      viridis;
  };
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      bc
      btop
      cacert
      cairo
      clang
      curl
      curlMinimal
      direnv
      duckdb
      gcc
      gettext
      gh
      git
      glibcLocales
      glpk
      gnupg
      gsl
      hdf5
      htop
      jags
      jq
      less
      libgcc
      libiconv
      libxml2
      locale
      nano
      nix
      openssl
      pandoc
      R
      toybox
      tree
      unzip
      zlib
      which;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs system_packages ];
    shellHook = "
export R_MAKEVARS_USER=/dev/null
export HDF5_USE_FILE_LOCKING=FALSE
export OPENBLAS_NUM_THREADS=1
printf "🔬 CoMMpass Multiple Myeloma Analysis Environment Ready
"
printf "📊 Packages loaded: %d CRAN + %d Bioconductor
" 
  "$(echo ${#r_pkgs[@]})" "$(echo ${#bioc_pkgs[@]})"
";
  }; 
in
  {
    inherit pkgs shell;
  }
