# This file was generated by default.R - DO NOT EDIT BY HAND
#
# Builds coMMpass as an installable R package derivation.
# Used by push_to_cachix.sh to push to johngavin cachix.
# Same rstats-on-nix pin as default.nix (2026-02-01).
#
# Usage:
#   nix-build package.nix --no-out-link
#   ./push_to_cachix.sh

let
  pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-02-01.tar.gz") {};
in pkgs.rPackages.buildRPackage {
  name = "coMMpass";
  src = ./.;
  propagatedBuildInputs = with pkgs.rPackages; [
    AnnotationDbi
    apeglm
    arrow
    aws_s3
    cli
    crew
    DBI
    dbplyr
    DESeq2
    dplyr
    DT
    duckdb
    edgeR
    fgsea
    GenomicDataCommons
    gert
    ggplot2
    gh
    glue
    here
    htmltools
    jsonlite
    knitr
    limma
    logger
    nanoparquet
    org_Hs_eg_db
    pkgdown
    plotly
    plumber
    quarto
    rmarkdown
    S4Vectors
    scales
    stringr
    SummarizedExperiment
    survival
    tarchetypes
    targets
    TCGAbiolinks
    testthat
    tibble
    tidyverse
    visNetwork
  ];
}

