name: 04 Build Website

on:
  workflow_run:
    workflows: ["03 Compute Analysis"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build-site:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: write
      actions: read

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v9
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: cachix/cachix-action@v14
        with:
          name: johngavin
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: rstats-on-nix

      - name: Check if previous runs exist
        id: runs-exist
        run: git ls-remote --exit-code --heads origin targets-runs
        continue-on-error: true

      - name: Checkout previous run
        if: steps.runs-exist.outcome == 'success'
        uses: actions/checkout@v4
        with:
          ref: targets-runs
          fetch-depth: 1
          path: .targets-runs

      - name: Restore output files from previous run
        if: steps.runs-exist.outcome == 'success'
        run: |
          nix-shell --pure default_ci.nix --run "Rscript -e 'for (dest in scan(\".targets-runs/.targets-files\", what = character())) {
            source <- file.path(\".targets-runs\", dest)
            if (!file.exists(dirname(dest))) dir.create(dirname(dest), recursive = TRUE)
            if (file.exists(source)) file.rename(source, dest)
          }'"

      - name: Build Website
        run: |
          echo "TAR_PROJECT=$PWD" >> $GITHUB_ENV
          nix-shell --pure default_ci.nix --run "Rscript build_site.R"

      - name: Upload Website
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: docs/

      - name: Upload failure artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: website-failure-${{ github.run_id }}
          path: _targets/meta/
          retention-days: 7
